### ISSUE TITLE
Registry: Impossible to edit long keys

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#156]
When a registry key is so long that it overflows the page, there is no way to get to the button to save the key. There should probably be a scroll bar in the edit window in such a case instead of just overflowing the edit window.

As an example, see the key couplingPts at registry/Jim/AliceBobRes/Cooldown151230/160222/Bc/:
![image](https://cloud.githubusercontent.com/assets/8183919/13265526/3655dda2-da28-11e5-8faa-28a629d4b917.png)

**Comment by joshm-3b6b58** [comment]
Well this wasn't a use case I'd considered. I think it should be an easy fix though...

**Comment by joshm-3b6b58** [comment]
Jim, could you do me a favor and past the contents of this registry key into here? My dev setup can't talk to the UCSB registry

**Comment by jwenner** [comment]
@joshmutus:

'couplingPts':

([-0.1175, -0.115, -0.1125, -0.11, -0.1075, -0.105, -0.1025, -0.1, -0.0975000000000001, -0.0950000000000001, -0.0925000000000001, -0.0900000000000001, -0.0875000000000001, -0.085, -0.0825, -0.08, -0.0775, -0.075, -0.0725, -0.07, -0.0675, -0.065, -0.0625, -0.06, -0.0575, -0.055, -0.0525, -0.05, -0.0475, -0.045, -0.0425, -0.04, -0.039, -0.038, -0.037, -0.036, -0.035, -0.034, -0.033, -0.032, -0.031, -0.03, -0.029, -0.028, -0.027, -0.026, -0.025, -0.024, -0.023, -0.022, -0.021, -0.02, -0.0195, -0.019, -0.0185, -0.018, -0.0175, -0.017, -0.0165, -0.016, -0.0155, -0.015, -0.0145, -0.014, -0.0135, -0.013, -0.0125, -0.012, -0.0115, -0.011, -0.0105, -0.00999999999999999, -0.00949999999999999, -0.00899999999999999, -0.00849999999999999, -0.00799999999999999, -0.00749999999999999, -0.00699999999999999, -0.00649999999999999, -0.00599999999999999, -0.00549999999999999, -0.00499999999999999, -0.00449999999999999, -0.00399999999999999, -0.00349999999999999, -0.00299999999999999, -0.00249999999999999, -0.00199999999999999, -0.00149999999999999, -0.000999999999999995, -0.000499999999999995, 4.33680868994202E-18], [76.823951029304 ns, 78.8356806636431 ns, 76.7978430583275 ns, 79.0078787067691 ns, 77.8735405789825 ns, 77.9511714403388 ns, 77.1189657707318 ns, 79.0817670996733 ns, 79.4194555888479 ns, 84.5073826047015 ns, 79.4981468713676 ns, 81.6288779542645 ns, 82.429554907223 ns, 84.7861935085675 ns, 83.7198812132735 ns, 84.9302256879315 ns, 85.5192909664944 ns, 90.3673183435841 ns, 92.0580289114109 ns, 89.0589123749336 ns, 98.2096565474107 ns, 96.6009975586282 ns, 104.459284242474 ns, 107.101728165906 ns, 111.922020948419 ns, 122.572422011619 ns, 121.472856855585 ns, 129.1896574607 ns, 136.649189527868 ns, 142.7721012852 ns, 156.392013976739 ns, 163.326923129191 ns, 174.51557065367 ns, 176.566545092947 ns, 186.780886672377 ns, 194.465359790356 ns, 196.373459727112 ns, 200.455591673097 ns, 199.971686280178 ns, 227.019165181139 ns, 221.871739376254 ns, 239.180087955827 ns, 253.437680812255 ns, 249.494536199669 ns, 258.271378375314 ns, 277.582339611261 ns, 292.192603460575 ns, 325.961578703415 ns, 328.37694372497 ns, 357.29170925367 ns, 359.871540879394 ns, 389.3860438564 ns, 420.506021157081 ns, 408.032182494229 ns, 446.43056469788 ns, 459.229851631737 ns, 472.051796825245 ns, 486.841985087697 ns, 516.488611521366 ns, 530.544422318611 ns, 596.409763856987 ns, 618.101822094037 ns, 619.752723753074 ns, 619.747827714218 ns, 654.710056942348 ns, 682.158557915657 ns, 752.66299810436 ns, 794.166473326562 ns, 769.703623644506 ns, 854.554659808841 ns, 956.492831876727 ns, 939.597407775205 ns, 1023.33431368626 ns, 1059.38717399402 ns, 1188.84128396815 ns, 1162.32837648089 ns, 1251.42710637438 ns, 1477.43029564101 ns, 1522.60856019716 ns, 1675.38470840057 ns, 1842.90248528451 ns, 2096.43852751129 ns, 2413.03807371831 ns, 2222.65878197139 ns, 2635.67615288763 ns, 2859.1139656715 ns, 3247.53195427376 ns, 3410.71193657984 ns, 3357.53857437511 ns, 3837.02928993146 ns, 4291.20794896869 ns, 5124.26430951624 ns])

**Comment by joshm-3b6b58** [comment]
@jwenner So, my local copy renders it as you would want on current master. It should look like this, correct?
![screenshot from 2016-02-23 14 40 41](https://cloud.githubusercontent.com/assets/8173925/13269241/9d226a38-da3b-11e5-8f78-92e3aad0bbd8.png)

![screenshot from 2016-02-23 14 40 48](https://cloud.githubusercontent.com/assets/8173925/13269246/a178d4dc-da3b-11e5-97f2-ce10fcf9fec1.png)

If so, it's just a matter of updating the polymer components and recompiling. 

@maffoo can you just run  `$ bower update paper-input` and recompile the server? I think this should fix it.

**Comment by jwenner** [comment]
@joshmutus, how you display the key is indeed what I'm asking for.

**Comment by maffoo** [comment]
I've updated the server, but it still doesn't work for me. @jwenner, can you give it another try yourself?

**Comment by maffoo** [comment]
@joshmutus, if we do need newer versions of the paper components, we should update `bower.json`. Right now the versions there are all just `^1.0.0`. It's never good for different people to be able to get different versions just based on when they last updated.

**Comment by jwenner** [comment]
@joshmutus and @maffoo, the version on matrix-reloaded still doesn't work for me either.

**Comment by maffoo** [comment]
Right now matrix-reloaded has 1.1.7:

```
$ bower list | grep paper-input
│ ├─┬ paper-input#1.1.7
│ │ ├─┬ paper-input#1.1.7
```

@joshmutus, what version are you using locally?

**Comment by joshm-3b6b58** [comment]
Just a sec, bower list is failing on me for some reason

```
 Failed to execute "git ls-remote --tags --heads git://github.com/nathanfaucett/require.js.git", exit code of #128 fatal: remote error:    Repository not found.
```

**Comment by joshm-3b6b58** [comment]
I can check the bower.json manually in the paper-input folder and I see I'm on 1.1.7

**Comment by joshm-3b6b58** [comment]
```
$ bower list | grep paper-input
│ ├─┬ paper-input#1.1.7
│ │ ├─┬ paper-input#1.1.7

$ bower list | grep polymer
│ │ └─┬ polymer#1.2.3 (1.3.0 available)
│ │ │ └── polymer#1.2.3

```

**Comment by joshm-3b6b58** [comment]
I double checked and I'm definitely on master. I've done a `gulp clean` to make sure my server's not in a strange state. I hope this isn't another mac vs. pc vs. linux rendering bug.

**Comment by joshm-3b6b58** [comment]
@maffoo to get bower.json updated to my current version numbers should I just run `bower init` ? There must a better way than manually inserting these version numbers.

**Comment by maffoo** [comment]
@joshmutus I think it's something like `bower install --save`

**Comment by joshm-3b6b58** [comment]
Ugh, looks like this has to be done for every component. I'll make an issue of this and do it later.

**Comment by joshm-3b6b58** [comment]
@maffoo have you tried rendering the registry key locally off of master? matrix-reloaded isn't on master, correct?

**Comment by joshm-3b6b58** [comment]
I think that screen resolution has something to do with this. When I opened the page on linux through my workstation the scrollbar didn't show up.

It seems like these dialogs are a big pain in general and we should think about going to popup windows or `window.prompt()`. I think @maffoo suggested this originally...

**Comment by jwenner** [comment]
As I mentioned in #97, I'm still encountering this issue in the version on matrix-reloaded. In fact, when I try to select part of the key in the edit screen to go up or down, what scrolls is the device page (listing all keys) instead of the edit screen.

**Comment by jwenner** [comment]
With the version that is now on matrix-reloaded as of this evening, this is now fixed. @maffoo, which version is on matrix-reloaded? If it is master, then we can go ahead and close this.

**Comment by maffoo** [comment]
Thanks for checking again, @jwenner. Yes, the version currently running on matrix is master, so I'll close this.
